### ISSUE TITLE
Not building on mac 10.15.4

### ISSUE THREAD

**Issue by louisfoster** [discordjs/opus#15]
Trying to install as of the time of this issue. Was working with `0.2.1`.
Getting messages of missing build:
```
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/discordjs/opus/releases/download/v0.3.1/opus-v0.3.1-node-v64-napi-v3-darwin-x64-unknown-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for @discordjs/opus@0.3.1 and node@10.16.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
```
which then leads to a build, but this seems to lead to:
```
Error: Cannot find module 'node-pre-gyp'
```
and after installing this, results in:
```
Error: Cannot find module @discordjs/opus/prebuild/node-v64-napi-v3-darwin-x64-unknown-{libc_version}/opus.node
```

Rolling back to 0.2.1 works.

**Comment by iCrawl** [comment]
I don't see how this can happen, are you sure it's listed as a dependency in the package.json and not as a devDepencendy?

**Comment by iCrawl** [comment]
Also I'd appreciate it if you don't just delete the issue template, its there for a reason

**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- @discordjs/opus version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by louisfoster** [comment]
> I don't see how this can happen, are you sure it's listed as a dependency in the package.json and not as a devDepencendy?

I don't think so, I'll look further into the cause.

> Also I'd appreciate it if you don't just delete the issue template, its there for a reason

Not sure what happened but my issue didn't seem to provide a template when I created it.
